"""اعتبارسنجی و ابزارهای مرتبط با قرارداد ستون‌های سیاست."""

from __future__ import annotations

import hashlib
import re
from typing import Iterable, Sequence

_RESERVED_PREFIXES: tuple[str, ...] = ("__",)
_RESERVED_EQUIVALENTS: tuple[str, ...] = ("index",)
_RESERVED_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^Unnamed(?::|\s)", re.IGNORECASE),
)
_INVALID_COLUMN_CHARS = re.compile(r"[\x00-\x1F]+")
_MAX_COLUMN_LENGTH = 64


def _normalize_name(raw: object) -> str:
    """نرمال‌سازی اولیهٔ نام ستون."""

    text = str(raw or "").strip()
    if not text:
        raise ValueError("selection reason columns must be non-empty strings")
    return text


def validate_policy_columns(columns: Sequence[object]) -> tuple[str, ...]:
    """تأیید می‌کند ستون‌های سیاست یکتا و با نام معتبر هستند."""

    cleaned: list[str] = []
    seen: set[str] = set()
    for raw in columns:
        name = _normalize_name(raw)
        lower = name.casefold()
        if lower in seen:
            raise ValueError(f"duplicate selection reason column detected: '{name}'")
        if any(name.startswith(prefix) for prefix in _RESERVED_PREFIXES):
            raise ValueError(f"column name '{name}' uses reserved prefix '__'")
        if lower in _RESERVED_EQUIVALENTS:
            raise ValueError(f"column name '{name}' clashes with reserved identifier 'index'")
        if any(pattern.match(name) for pattern in _RESERVED_PATTERNS):
            raise ValueError(f"column name '{name}' resembles pandas autogenerated headers")
        if _INVALID_COLUMN_CHARS.search(name):
            raise ValueError(f"column name '{name}' contains control characters")
        if len(name) > _MAX_COLUMN_LENGTH:
            raise ValueError(
                f"column name '{name}' exceeds maximum length {_MAX_COLUMN_LENGTH} characters"
            )
        seen.add(lower)
        cleaned.append(name)
    return tuple(cleaned)


def compute_schema_hash(columns: Iterable[str]) -> str:
    """هش SHA-1 برای لیست ستون‌ها را جهت ممیزی برمی‌گرداند."""

    joined = ",".join(str(name) for name in columns)
    return hashlib.sha1(joined.encode("utf-8")).hexdigest()


__all__ = [
    "compute_schema_hash",
    "validate_policy_columns",
]
